version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:2022.09
    parallelism: 20
    steps:
      - checkout
      - setup_remote_docker:

      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t mbc . --progress=plain
